export function extractYouTubeVideoId(url: string): string | null {
  const trimmed = url.trim()
  if (!trimmed) return null

  const patterns = [
    /youtube\.com\/shorts\/([^?&/]+)/,
    /youtube\.com\/embed\/([^?&/]+)/,
    /youtube\.com\/watch\?v=([^?&/]+)/,
    /youtu\.be\/([^?&/]+)/,
  ]

  for (const pattern of patterns) {
    const match = trimmed.match(pattern)
    if (match?.[1]) return match[1]
  }

  return null
}

export function isYouTubeUrl(url: string) {
  return extractYouTubeVideoId(url) !== null
}

/** True when the poster was auto-filled from YouTube (not a custom upload). */
export function isAutoYouTubePoster(url: string | null | undefined) {
  if (!url?.trim()) return false
  return url.includes('i.ytimg.com/vi/') || url.includes('img.youtube.com/vi/')
}

/**
 * Vertical Shorts thumbnail from YouTube's CDN (not generated by this app).
 * `cacheKey` busts browser cache when the story video URL changes.
 */
export function youTubeThumbnailUrl(videoId: string, variant: 'oar' | 'hq' = 'oar', cacheKey?: string) {
  const file = variant === 'oar' ? 'oardefault.jpg' : 'hqdefault.jpg'
  const base = `https://i.ytimg.com/vi/${videoId}/${file}`
  if (!cacheKey) return base
  return `${base}?v=${encodeURIComponent(cacheKey)}`
}

export function resolveStoryPosterUrl(story: { imageUrl: string; videoUrl?: string | null }) {
  const videoUrl = story.videoUrl?.trim() || ''
  const youTubeId = videoUrl ? extractYouTubeVideoId(videoUrl) : null
  if (youTubeId) return youTubeThumbnailUrl(youTubeId, 'oar', videoUrl)
  return story.imageUrl
}

/** Poster URL to persist when saving a story in admin. */
export function resolveStoryPosterForSave(videoUrl: string, imageUrl?: string | null) {
  const youTubeId = extractYouTubeVideoId(videoUrl)
  const customPoster = imageUrl?.trim() || ''

  if (youTubeId) {
    if (customPoster && !isAutoYouTubePoster(customPoster)) return customPoster
    return youTubeThumbnailUrl(youTubeId, 'hq', videoUrl)
  }

  return customPoster
}

type YouTubeEmbedOptions = {
  autoplay?: boolean
  controls?: boolean
  loop?: boolean
}

export function youTubeEmbedUrl(videoId: string, options: YouTubeEmbedOptions = {}) {
  const { autoplay = false, controls = true, loop = false } = options
  const params = new URLSearchParams({
    autoplay: autoplay ? '1' : '0',
    mute: '1',
    controls: controls ? '1' : '0',
    playsinline: '1',
    modestbranding: '1',
    rel: '0',
  })

  if (loop) {
    params.set('loop', '1')
    params.set('playlist', videoId)
  }

  return `https://www.youtube.com/embed/${videoId}?${params.toString()}`
}
