export const adminNavLink = 'block rounded-xl px-3 py-2 text-sm font-medium text-white/80 hover:bg-white/5 hover:text-white'
export const adminNavLinkActive = 'bg-white/10 text-dq-gold'
export const adminTable = 'min-w-full text-left text-sm text-dq-black'
export const adminTh = 'border-b border-[#e5e5e5] px-3 py-3 text-xs font-semibold uppercase tracking-wide text-[#737373]'
export const adminTd = 'border-b border-[#f0f0f0] px-3 py-3 align-top text-dq-black'
