/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BackendRouteRouteImport } from './routes/backend/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendIndexRouteImport } from './routes/backend/index'
import { Route as BackendVentureRouteImport } from './routes/backend/venture'
import { Route as BackendStoriesRouteImport } from './routes/backend/stories'
import { Route as BackendSiteRouteImport } from './routes/backend/site'
import { Route as BackendSignupRouteImport } from './routes/backend/signup'
import { Route as BackendQuranWikiRouteImport } from './routes/backend/quran-wiki'
import { Route as BackendProductsRouteImport } from './routes/backend/products'
import { Route as BackendLoginRouteImport } from './routes/backend/login'
import { Route as BackendHeroRouteImport } from './routes/backend/hero'
import { Route as BackendArticlesRouteImport } from './routes/backend/articles'

const BackendRouteRoute = BackendRouteRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendIndexRoute = BackendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendVentureRoute = BackendVentureRouteImport.update({
  id: '/venture',
  path: '/venture',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendStoriesRoute = BackendStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSiteRoute = BackendSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendSignupRoute = BackendSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendQuranWikiRoute = BackendQuranWikiRouteImport.update({
  id: '/quran-wiki',
  path: '/quran-wiki',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendProductsRoute = BackendProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendLoginRoute = BackendLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendHeroRoute = BackendHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => BackendRouteRoute,
} as any)
const BackendArticlesRoute = BackendArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => BackendRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backend': typeof BackendRouteRouteWithChildren
  '/backend/articles': typeof BackendArticlesRoute
  '/backend/hero': typeof BackendHeroRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/quran-wiki': typeof BackendQuranWikiRoute
  '/backend/signup': typeof BackendSignupRoute
  '/backend/site': typeof BackendSiteRoute
  '/backend/stories': typeof BackendStoriesRoute
  '/backend/venture': typeof BackendVentureRoute
  '/backend/': typeof BackendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backend/articles': typeof BackendArticlesRoute
  '/backend/hero': typeof BackendHeroRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/quran-wiki': typeof BackendQuranWikiRoute
  '/backend/signup': typeof BackendSignupRoute
  '/backend/site': typeof BackendSiteRoute
  '/backend/stories': typeof BackendStoriesRoute
  '/backend/venture': typeof BackendVentureRoute
  '/backend': typeof BackendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backend': typeof BackendRouteRouteWithChildren
  '/backend/articles': typeof BackendArticlesRoute
  '/backend/hero': typeof BackendHeroRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/products': typeof BackendProductsRoute
  '/backend/quran-wiki': typeof BackendQuranWikiRoute
  '/backend/signup': typeof BackendSignupRoute
  '/backend/site': typeof BackendSiteRoute
  '/backend/stories': typeof BackendStoriesRoute
  '/backend/venture': typeof BackendVentureRoute
  '/backend/': typeof BackendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backend'
    | '/backend/articles'
    | '/backend/hero'
    | '/backend/login'
    | '/backend/products'
    | '/backend/quran-wiki'
    | '/backend/signup'
    | '/backend/site'
    | '/backend/stories'
    | '/backend/venture'
    | '/backend/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backend/articles'
    | '/backend/hero'
    | '/backend/login'
    | '/backend/products'
    | '/backend/quran-wiki'
    | '/backend/signup'
    | '/backend/site'
    | '/backend/stories'
    | '/backend/venture'
    | '/backend'
  id:
    | '__root__'
    | '/'
    | '/backend'
    | '/backend/articles'
    | '/backend/hero'
    | '/backend/login'
    | '/backend/products'
    | '/backend/quran-wiki'
    | '/backend/signup'
    | '/backend/site'
    | '/backend/stories'
    | '/backend/venture'
    | '/backend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackendRouteRoute: typeof BackendRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/backend': {
      id: '/backend'
      path: '/backend'
      fullPath: '/backend'
      preLoaderRoute: typeof BackendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/': {
      id: '/backend/'
      path: '/'
      fullPath: '/backend/'
      preLoaderRoute: typeof BackendIndexRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/venture': {
      id: '/backend/venture'
      path: '/venture'
      fullPath: '/backend/venture'
      preLoaderRoute: typeof BackendVentureRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/stories': {
      id: '/backend/stories'
      path: '/stories'
      fullPath: '/backend/stories'
      preLoaderRoute: typeof BackendStoriesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/site': {
      id: '/backend/site'
      path: '/site'
      fullPath: '/backend/site'
      preLoaderRoute: typeof BackendSiteRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/signup': {
      id: '/backend/signup'
      path: '/signup'
      fullPath: '/backend/signup'
      preLoaderRoute: typeof BackendSignupRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/quran-wiki': {
      id: '/backend/quran-wiki'
      path: '/quran-wiki'
      fullPath: '/backend/quran-wiki'
      preLoaderRoute: typeof BackendQuranWikiRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/products': {
      id: '/backend/products'
      path: '/products'
      fullPath: '/backend/products'
      preLoaderRoute: typeof BackendProductsRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/login': {
      id: '/backend/login'
      path: '/login'
      fullPath: '/backend/login'
      preLoaderRoute: typeof BackendLoginRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/hero': {
      id: '/backend/hero'
      path: '/hero'
      fullPath: '/backend/hero'
      preLoaderRoute: typeof BackendHeroRouteImport
      parentRoute: typeof BackendRouteRoute
    }
    '/backend/articles': {
      id: '/backend/articles'
      path: '/articles'
      fullPath: '/backend/articles'
      preLoaderRoute: typeof BackendArticlesRouteImport
      parentRoute: typeof BackendRouteRoute
    }
  }
}

interface BackendRouteRouteChildren {
  BackendArticlesRoute: typeof BackendArticlesRoute
  BackendHeroRoute: typeof BackendHeroRoute
  BackendLoginRoute: typeof BackendLoginRoute
  BackendProductsRoute: typeof BackendProductsRoute
  BackendQuranWikiRoute: typeof BackendQuranWikiRoute
  BackendSignupRoute: typeof BackendSignupRoute
  BackendSiteRoute: typeof BackendSiteRoute
  BackendStoriesRoute: typeof BackendStoriesRoute
  BackendVentureRoute: typeof BackendVentureRoute
  BackendIndexRoute: typeof BackendIndexRoute
}

const BackendRouteRouteChildren: BackendRouteRouteChildren = {
  BackendArticlesRoute: BackendArticlesRoute,
  BackendHeroRoute: BackendHeroRoute,
  BackendLoginRoute: BackendLoginRoute,
  BackendProductsRoute: BackendProductsRoute,
  BackendQuranWikiRoute: BackendQuranWikiRoute,
  BackendSignupRoute: BackendSignupRoute,
  BackendSiteRoute: BackendSiteRoute,
  BackendStoriesRoute: BackendStoriesRoute,
  BackendVentureRoute: BackendVentureRoute,
  BackendIndexRoute: BackendIndexRoute,
}

const BackendRouteRouteWithChildren = BackendRouteRoute._addFileChildren(
  BackendRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackendRouteRoute: BackendRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
